name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Run Deployment Script
        uses: ./.github/workflows/deploy.yml
        with:
          catalog: "hive_metastore"
          env: "dev"
          environmentName: ${{ secrets.DEV_ENV_NAME }}
          resourceGroupName: ${{ secrets.DEV_RESOURCE_GRP_NAME }}
          serviceConnection: ${{ secrets.AZURE_CREDENTIALS }}
          notebookPath: "notebooks"
